[PATCH] Fix typing issues introduced with MyPy 0.750
Current issues reported by MyPy are:
```
conformity/sphinx_ext/autodoc.py:555: error: Value of type "Optional[Tuple[Any, ...]]" is not indexable
conformity/sphinx_ext/autodoc.py:570: error: Value of type "Optional[Dict[str, Any]]" is not indexable
Found 2 errors in 1 file (checked 40 source files)
```